# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f63764631a9740344c39b795d28830823e6b1607673191e01ad88f8eee5047e534703d1176c1b5795fd066ab3a9a7a50aad7997f49b912e6d1b7495f42a0ddf5

test:
  secret_key_base: 7db9a9b292906ed9f3b0b4d1a3c9ee77b2c55a323b394521cf5169b678ce82209e39da6bd66fac1be3705afa074205d0a2a5a7b76a12969335cf80e857f2c52a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
